# Commands to start on workspace startup
tasks:
  - name: Init Script
    init: python --version
    openMode: tab-before
  - name: Run script file
    command: python ./run-script.py
    openMode: tab-after
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview